### PR TITLE
Added Heap Sort

### PR DESCRIPTION
**Pull request by harshitgupta2000**

### CODE REVIEW

**Comment by SakshamAgrwl** [comment]
@harshitgupta2000 It's a sincere request to you please don't add duplicate file. I'm keeping a check on all of the programs and you are always creating 2 files for a single sorting algorithm. Please delete your heap.cpp and bubble.cpp asap.

**Comment by harshitgupta2000** [comment]
Actually it is in C and C++ thats why there are 2 duplicate looking files

**Comment by harshitgupta2000** [comment]
Please approve one and i am deleting another

**Comment by SakshamAgrwl** [comment]
@harshitgupta2000 Create a new PR with the suggested changes. Don't worry, it will be merged but first you create a new PR with the suggested changes.

**Comment by harshitgupta2000** [comment]
Ok I am creating a new PR with unique name like heaps.cpp in C++

**Pull request closed without merging**
