### PR TITLE
Creating function to find PerimeterOfRectangle

### PR DESCRIPTION
**Pull request by rishikasoni67**

### CODE REVIEW

**Comment by SakshamAgrwl** [comment]
@rishikasoni67 Please star this repo, the star symbol can be found beside the fork symbol.

**Comment by rishikasoni67** [comment]
👍

**Comment by rishikasoni67** [comment]
Sure .
One request, if you could label this as hactoberfect-acepted

**Comment by SakshamAgrwl** [comment]
I have labelled it as hacktoberfest. Don't know how to label as hacktoberfest-accepted. If you know this then open this issue and start solving this issue or just create a new issue related to this and somebody will do it.

**Comment by SakshamAgrwl** [comment]
@rishikasoni67 Please do let me know now if you can view the hacktoberfest-label and if your PR is accepted now.

**Comment by rishikasoni67** [comment]
Yes, I can view the label now.
Thank you .. @SakshamAgrwl

**Comment by SakshamAgrwl** [comment]
@rishikasoni67 I would like to know if your PR is accepted for hacktoberfest or not.

**Comment by rishikasoni67** [comment]
@SakshamAgrwl  I am new to Hactoberfest and even created PRs for the first time and simply just know that after being merged or labeled as **hactoberfest-accepted**, PRs are accepted for Hactoberfest. Moreover, after passing the review period of 14 days this will be accepted and a tick ✔️ will be shown on my Hactoberfest profile.

**Comment by SakshamAgrwl** [comment]
@rishikasoni67 Yes, you are correct, I'm updating the readme.md file to make it more friendly for the new comers which makes it easy for anyone to create a new PR. Feel free to create issues for this repo so that many people can work on those issues.

**Comment by rishikasoni67** [comment]
@SakshamAgrwl  👍

**Comment by SakshamAgrwl** [comment]
Hey @rishikasoni67 i have updated the readme file of this repository. Go ahead and view it and you will get more familiar to this repo. Also, please start creating new issues for this repo.

**Pull request merged**
