### PR TITLE
Create sumOfElementsOfArray.cpp

### PR DESCRIPTION
**Pull request by anantbharti**
Function which returns sum of elements of Array. Please merge it for Hacktoberfest.

### CODE REVIEW

**Comment by SakshamAgrwl** [comment]
@anantbharti congrats for getting ur PR merged. A request to you will be to  ⭐ this repository if you feel that it was of any help to you.

**Comment by anantbharti** [comment]
Hey @SakshamAgrwl  Can you please add hacktoberfest-accepted label as I am participating in Hacktoberfest2020.

**Comment by SakshamAgrwl** [comment]
@anantbharti  Already added pls check the about section of the repo at the right corner

**Comment by SakshamAgrwl** [comment]
@anantbharti please do keep me updated if the repository is eligible for hacktoberfest as I have already added the labels and updated the readme.md

**Comment by anantbharti** [comment]
@saks1209am   Yeah Sure, Thanks a lot.

**Pull request merged**
