### PR TITLE
Added Meta Strings solution in String

### PR DESCRIPTION
**Pull request by tanya-0708**
I have added Meta Strings solution of GFG in Strings folder. My solution is in C++. Please merge it.

### CODE REVIEW

**Comment by SakshamAgrwl** [comment]
@tanya-0708 Can you please explain me what is a meta string?. I really dont know

**Comment by SakshamAgrwl** [comment]
Congrats @tanya-0708 . Make sure you open up more issues in this repository and show your love for this repo by giving it a ⭐

**Comment by tanya-0708** [comment]
Hey! Meta strings problem is available on gfg.
I am adding link to it
Link :
https://www.geeksforgeeks.org/meta-strings-check-two-strings-can-become-swap-one-string/
I hope that you will be able to understand the problem by this.
Thank you :)

**Comment by SakshamAgrwl** [comment]
@tanya-0708 I didn't know the term but i understood your code, that's why I had merged your PR. Anyways, keep up the good work and if you feel this repository is good then make sure you ⭐ it.

**Pull request merged**
